@{
    RootModule        = 'IMPACT_Docker_GUI.psm1'
    ModuleVersion     = '2.0.0'
    GUID              = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
    Author            = 'IMPACT NCD Germany'
    Description       = 'Core functions for the IMPACT Docker GUI – container lifecycle, SSH helpers, theming, and GitHub integration.'
    PowerShellVersion = '7.0'
    FunctionsToExport = @(
        'Enable-NonInteractiveMode'
        'Disable-NonInteractiveMode'
        'Test-NonInteractiveMode'
        'Initialize-Logging'
        'Write-Log'
        'Get-BuildInfo'
        'New-SessionState'
        'Ensure-PowerShell7'
        'Get-RemoteHostString'
        'Set-DockerSSHEnvironment'
        'Get-DockerContextArgs'
        'Convert-PathToDockerFormat'
        'Test-RemoteSSHKeyFiles'
        'Write-RemoteContainerMetadata'
        'Remove-RemoteContainerMetadata'
        'Read-RemoteContainerMetadata'
        'Get-ContainerRuntimeInfo'
        'Get-YamlPathValue'
        'Test-AndCreateDirectory'
        'Get-GitRepositoryState'
        'Show-GitCommitDialog'
        'Invoke-GitChangeDetection'
        'Set-FormCenterOnCurrentScreen'
        'Initialize-ThemePalette'
        'Apply-ThemeToForm'
        'Style-Label'
        'Style-TextBox'
        'Style-CheckBox'
        'Style-Button'
        'Style-InfoBox'
        'Test-StartupPrerequisites'
        'Ensure-Prerequisites'
        'Show-CredentialDialog'
        'Ensure-SshAgentRunning'
        'Remove-SshConfigHostBlock'
        'Ensure-SshConfigEntry'
        'Ensure-GitKeySetup'
        'Select-Location'
        'Build-DockerRunCommand'
        'Test-DockerDaemonReady'
        'Start-DockerDesktopIfNeeded'
        'Add-GitHubSshKey'
        'Remove-GitHubSshKey'
    )
    CmdletsToExport   = @()
    VariablesToExport  = @()
    AliasesToExport    = @()
    PrivateData       = @{ PSData = @{} }
}
